ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Contexto y alcance

Esta sección describe el entorno en el que opera el sistema YOVI y las interacciones con actores externos.
El sistema se presenta como una caja negra, mostrando únicamente sus relaciones con el exterior.

=== Contexto de negocio

[plantuml]
----
@startuml
left to right direction
skinparam rectangleStyle rounded
title YOVI - Diagrama de contexto de negocio

actor Jugador
rectangle "Sistema YOVI" as system
actor Bot

' === Enlaces ocultos para forzar la posición central ===
Jugador -[hidden]right- system
system -[hidden]right- Bot

Jugador --> system : Se registra y juega
system --> Jugador : Muestra estado del juego y estadísticas
Bot --> system : Juega mediante la API
system --> Bot: Provee info. de partidas y jugadores
@enduml
----

El *sistema YOVI* proporciona al jugador información sobre el estado del juego y diferentes estadísticas.

El actor externo principal del sistema es el *jugador*, que puede registrarse y participar en partidas.

Además, existe el actor de *bot externo*, el cual se conectra con el API de la aplicación para jugar y para obtener información de personajes y partidas.

=== Contexto técnico

[plantuml]
----
@startuml
left to right direction
skinparam rectangleStyle rounded

title YOVI - Diagrama de contexto técnico

actor Jugador
rectangle "Sistema YOVI" as system
actor Bot

' === Enlaces ocultos para forzar la posición central ===
Jugador -[hidden]right- system
system -[hidden]right- Bot

' === Conexiones reales ===
Jugador --> system : Peticiones HTTP/HTTPS
Bot --> system : Peticiones HTTP/HTTPS + JSON

@enduml
----

El sistema YOVI expone una interfaz basada en servicios web accesibles mediante protocolo HTTP/HTTPS.

Los actores externos interactúan con el sistema mediante peticiones y respuestas estructuradas en formato JSON.


==== Mapeo de entrada/salida a canales

[cols="1,1,2,2", options="header"]
|===
| Actor | Canal | Entrada al sistema | Salida del sistema

| Jugador
| HTTP/HTTPS
| Datos de registro, autenticación, acciones del juego
| Estado del juego, resultados, estadísticas

| Bot
| HTTP/HTTPS + JSON
| Acciones automatizadas del juego
| Estado del juego y resultados
|===
