ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Requisitos de calidad


ifdef::arc42help[]
[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.


.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****
endif::arc42help[]

=== Árbol de Calidad

ifdef::arc42help[]
[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****
endif::arc42help[]
[plantuml,"arbol-calidad",png]
----
@startmindmap
+ Yovi
++ Efectividad
++ Calidad del producto
+++_ Exactitud
++ Rendimiento
+++_ Comportamiento temporal
++ Compatibilidad
+++_ Coexistencia
++ Usabilidad
+++_ Aprendizaje
+++_ Estética de IU
+++_ Accesibilidad
-- Confiabilidad
---_ Disponibilidad
-- Seguridad
---_ Confidencialidad
-- Mantibilidad
---_ Modularidad
-- Portabilidad
---_ Adaptabilidad
---_ Reemplazabilidad
@endmindmap
----


=== Escenarios de Calidad

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
endif::arc42help[]

Usabilidad
[cols="1,1,1,1,1,1" options="header"]
|===
| **Fuente** | **Estímulo** | **Artefacto** | **Entorno** | **Respuesta** | **Medida de la respuesta**
| Usuario | Intenta acceder a la pantalla de juego | Interfaz de usuario | Operación normal | Número de pasos realizados | <= 3 pasos
|===

Accesibilidad
[cols="1,1,1,1,1,1" options="header"]
|===
| **Fuente** | **Estímulo** | **Artefacto** | **Entorno** | **Respuesta** | **Medida de la respuesta**
| Usuario | Juega una partida con problemas de visión |  Interfaz de usuario | Operación normal | Elementos visualizados de forma clara | >90% elementos
|===

Rendimiento
[cols="1,1,1,1,1,1" options="header"]
|===
| **Fuente** | **Estímulo** | **Artefacto** | **Entorno** | **Respuesta** | **Medida de la respuesta**
| Usuario | Realiza una partida|  Interfaz de usuario | Operación normal | Tiempo de respuesta media por acción| <0.5 segundos
| Bot | Interactúa con la API |  API para bots externos | Operación normal | Tiempo de respuesta media por acción| <1 segundo
|===

Mantenibilidad
[cols="1,1,1,1,1,1" options="header"]
|===
| **Fuente** | **Estímulo** | **Artefacto** | **Entorno** | **Respuesta** | **Medida de la respuesta**
| Stakeholder | Sugiere añadir un nuevo modo de juego | Componentes de la aplicación | Operación de modificación | Coste de añadir nuevo modo de juego| Proporcional al tiempo usual de desarrollo, sin coste adicional por deuda técnica
|===

Seguridad
[cols="1,1,1,1,1,1" options="header"]
|===
| **Fuente** | **Estímulo** | **Artefacto** | **Entorno** | **Respuesta** | **Medida de la respuesta**
| Usuario | Se registra en la aplicación | Interfaz de registro | Operación normal | Privacidad de los datos introducidos | Datos cifrados y accesibles solo por el propio usuario
| Bot | Accede a información de usuarios | API de usuarios | Operación normal | Privacidad de los datos solicitados | Solo mostrar información no sensible
|===

Exactitud
[cols="1,1,1,1,1,1" options="header"]
|===
| **Fuente** | **Estímulo** | **Artefacto** | **Entorno** | **Respuesta** | **Medida de la respuesta**
| Usuario | Realiza una jugada| Interfaz de juego | Operación normal | Consistencia de la operación | La respuesta debe ser siempre la esperada por las reglas del juego
| Bot | Realiza una jugada| API de juego| Operación normal | Consistencia de la operación | La respuesta debe ser siempre la esperada por las reglas del juego
|===

